apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\tienl\Desktop\CSIT314\kompose.exe --file docker-compose.yml
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: judge0-server
  name: judge0-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: judge0-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\tienl\Desktop\CSIT314\kompose.exe --file docker-compose.yml
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: judge0-server
    spec:
      containers:
      - image: judge0/judge0:latest
        imagePullPolicy: ""
        name: server
        ports:
        - containerPort: 2358
        resources: {}
        securityContext:
          privileged: true
      - image: postgres:13.0
        imagePullPolicy: ""
        name: db
        envFrom:
          - configMapRef:
              name: postgres-config
        resources: { }
      - image: redis:6.0
        imagePullPolicy: ""
        name: judge0-redis
      restartPolicy: Always
      serviceAccountName: ""
status: {}
