apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\tienl\Desktop\CSIT314\kompose.exe --file docker-compose.yml
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: judge0-server
  name: judge0-server
spec:
  type: LoadBalancer
  ports:
    - port: 2358
      targetPort: 2358
      protocol: TCP
      name: http
  selector:
    io.kompose.service: judge0-server
status:
  loadBalancer: {}
