apiVersion: v1
kind: ConfigMap
metadata:
  name: workers-config
  labels:
    io.kompose.service: workers
data:
  RAILS_MAX_THREADS: "2"
  RAILS_SERVER_PROCESSES: "3"
  MAX_QUEUE_SIZE: "1000"
  COUNT: "3"
