apiVersion: v1
kind: ConfigMap
metadata:
  name: workers-config
  labels:
    io.kompose.service: workers
data:
  RAILS_MAX_THREADS: "100"
  RAILS_SERVER_PROCESSES: "60"
  MAX_QUEUE_SIZE: "1000"
  COUNT: "60"
