apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-service
  labels:
    app: test-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: test-service
    spec:
      containers:
        - name: test-service
          ports:
            - containerPort: 9090
          imagePullPolicy:  Always
          image: asia.gcr.io/aqueous-tube-251208/test-service:0.1.0
          env:
            - name: JUDGE0-SERVICE
              value: http://10.3.250.2:2358
          envFrom:
            - secretRef:
                name: data-source
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.22.0
          command: ["/cloud_sql_proxy","-instances=aqueous-tube-251208:us-central1:judge-service-test=tcp:5432",
          "-credential_file=/var/google/secret/key.json"]
          volumeMounts:
            - mountPath: /var/google/secret
              name: owner-key
              readOnly: true
        - image: redis:6.0
          imagePullPolicy: ""
          name: test-service-redis
      volumes:
        - name: owner-key
          secret:
            secretName: owner-key
  selector:
    matchLabels:
      app: test-service
