apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
spec:
  rules:
    - host: "tdlinh2712.github.io"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: test-loadbalancer-service
                port:
                  number: 9090